name = sunken_spoils
description = Adds new fishing rods and a chance to catch new loot crates
depends = mcl_core, mcl_tools, mcl_fishing, mcl_loot, mcl_sounds, mcl_enchanting, mcl_armor, mcl_beacons
