name = sunken_spoils
supported_games = mineclonia
description = Adds new fishing rods, new abyssil metal and loot crates that are acquired from fishing.
depends = mcl_core, mcl_tools, mcl_fishing, mcl_loot, mcl_sounds, mcl_enchanting, mcl_armor, mcl_beacons, awards, mcl_item_entity
